behaviors:
  BasicSAC:
    trainer_type: sac
    hyperparameters:
      batch_size: 128
      buffer_size: 1280
      learning_rate: 3.0e-5
      learning_rate_schedule: linear
      buffer_init_steps: 1000
      tau: 0.005
      steps_per_update: 10
      save_replay_buffer: true
      init_entcoef: 0.5
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 5
    reward_signals: 
      extrinsic:
        strength: 1.0
        gamma: 0.999
        network_settings:
          vis_encode_type: simple
          normalize: true
          hidden_units: 512
          num_layers: 5


    max_steps: 500000
    time_horizon: 64
    summary_freq: 5000