behaviors:
  BasicAI:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 1280
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 10
      learning_rate_schedule: linear
    network_settings:
      vis_encode_type: simple
      normalize: true
      hidden_units: 512
      num_layers: 5

      

    reward_signals: 
      extrinsic:
        strength: 1.0
        gamma: 0.999
        network_settings:
          vis_encode_type: simple
          normalize: true
          hidden_units: 512
          num_layers: 5



    max_steps: 750000
    time_horizon: 64
    summary_freq: 5000
    checkpoint_interval: 100000